### ISSUE TITLE
Simpler version that works on a 16Kb nrf51?

### ISSUE THREAD

**Issue by aguaviva** [dakhnod/BLEnky#18]
I'd be nice to have a version with less features that works on a 16Kb verion ( I presume this one only works on a 32Kb, right?)

**Comment by dakhnod** [comment]
nope, the base one is for qfaa chips, those should be smaller nrf51822 ones

**Comment by dakhnod** [comment]
@aguaviva While I mostly work with the base version, it does miss features like Pairing and Passkeys.

**Comment by dakhnod** [comment]
I am going to assume this as answered.

**Comment by aguaviva** [comment]
Hi, the makefile defaults to xxac(32Kb RAM) how do suggest compiling this firmware for xxaa (16Kb RAM) chips?

**Comment by dakhnod** [comment]
Where do you see xxac in the makefile?

**Comment by dakhnod** [comment]
`LINKER_SCRIPT  := src/linker/nrf51822_qfaa.ld` is what counts

**Comment by aguaviva** [comment]
> Where do you see xxac in the makefile?

in the very first line, sure is optional, but wasn't sure if changing it would make it work with nrf51822. 
```
TARGETS          ?= nrf51822_xxac
```
Also it seems it is using an s130 which I, mistakenly, thought it was not supported  (I stuck to s110 in my projects but now I might give it a go )

Many thanks for clarifying, I hope this helps other people too.

**Comment by dakhnod** [comment]
No problem! Mind sharing what you're planning with BLEnky?

**Comment by aguaviva** [comment]
I have a few nrf51822 around and it looks like your firmware would put them to a good use. I don't have any use case yet but I am sure I will find something useful, for now I want to compile the firmware and give it go. I'll keep you posted with whatever I come up :)

**Comment by dakhnod** [comment]
Thanks! I would recommend flashing via my bootloader

**Comment by aguaviva** [comment]
A nice feature would control an IR LED via BLE, that way you can control old appliances (AC, old stereos) with the phone and/or automate things with a home assistant. The IR code would be transferred via BLE by the phone to the device, keeping it this way as simple and generic as possible.

**Comment by dakhnod** [comment]
Interesting thought. You could use gpioASM for that, but that has a resolution of 1ms...

What are the timings of such a IR signal?

**Comment by aguaviva** [comment]
you can find lots of timing codes in this arduino lib https://github.com/Arduino-IRremote/Arduino-IRremote/tree/master/src

**Comment by dakhnod** [comment]
Maybe this is doable with pwm and gpioASM

**Comment by aguaviva** [comment]
I like to keep things as easy as possible, so if I was to do this I would probably start from scratch using one of my samples.

**Comment by dakhnod** [comment]
PWM is built into BLEnky, so is a gpioASM runtime. So writing C code would probably not be simpler...
